### PR TITLE
Support Terraform version >= 0.12.x

### LINKED ISSUE #3: default_tag resource with count argument couse error
> Error: Missing resource instance key
> 
>   on .terraform/modules/droplet/terraform-digitalocean-modules-terraform-digitalocean-droplet-2e6b972/main.tf line 50, in resource "digitalocean_droplet" "droplet":
>   50:   tags               = ["${compact(concat(var.tags, list(digitalocean_tag.default_tag.id)))}"]
> 
> Because digitalocean_tag.default_tag has "count" set, its attributes must be
> accessed on specific instances.
> 
> For example, to correlate with indices of a referring resource, use:
>     digitalocean_tag.default_tag[count.index]

### PR DESCRIPTION
**Pull request by DaemonDude23**
This PR updates the module, its three examples, and the README to be compatible with the newer version of Terraform.

I've run it through the Terraform formatter (However, `terraform_docs` for `0.12.x`+ isn't [yet supported](https://github.com/segmentio/terraform-docs/issues/62)). I updated the README by hand for loadbalancer-related values. The DigitalOcean provider has likely changed since this module was released, and some inputs may have changed.

Let me know if there's any changes needed.

(This fixes  #3 )

### CODE REVIEW

**Comment by js-timbirkett** [comment]
Thanks @chicken231 - I haven't checked in on this repo for a while. I'll take a look at this very soon.

**Comment by DaemonDude23** [comment]
Sounds good, thanks. I checked out that `terraform_docs` issue, looks like it supports TF `0.12` now. If I get time this weekend I'll try running it against my fork.

**Comment by tsujamin** [comment]
Is there an ETA on this merge? Currently blocking a 0.12 project for me 😢

**Comment by pysysops** [comment]
This is merged, I'm just going to update anything that needs it and release to the registry 😸

**Comment by pysysops** [comment]
@tsujamin @chicken231  - I've released this: https://registry.terraform.io/modules/terraform-digitalocean-modules/droplet/digitalocean/1.0.1

**Pull request merged**
